// Differential test of the version 8 second leg (FIPS 205 SLH-DSA-SHA2-192f).
//
// The node signs and checks the v8 leg with lattice-slh-dsa 0.4.0. RustCrypto
// `slh-dsa` 0.1.0 is a second, independent implementation of final FIPS 205. The
// two must agree byte for byte: on the NIST ACVP vectors, on fresh keys signed by
// either side, and on the second leg of a whole v8 record. Anyone who checks a v8
// leg with the other implementation then gets the node's verdict.

use dilithium::safe_api::DilithiumKeyPair;
use elara_record::pqc::{verify_second_leg, SignedFormat, ALG_SLH_DSA_SHA2_192F};
use elara_record::record::{Classification, ValidationRecord};
use rustcrypto_slh_dsa::signature::{Signer, Verifier};
use rustcrypto_slh_dsa::{Sha2_192f, Signature, SigningKey, VerifyingKey};
use slh_dsa::params::SLH_DSA_SHA2_192F;
use slh_dsa::safe_api::SlhDsaKeyPair;

const INTERNAL: &str = include_str!("vectors/acvp_slhdsa192f_sigver.txt");
const EXTERNAL: &str = include_str!("vectors/acvp_slhdsa192f_external_sigver.txt");
const V8_LEG: &str = include_str!("vectors/acvp_slhdsa192f_v8_leg.txt");
const V8: SignedFormat = SignedFormat::Record(8);

/// One vector line: `tcId|P/F|reason|hex…`, with exactly `hex_fields` hex fields.
struct Case {
    tc: String,
    expect: bool,
    fields: Vec<Vec<u8>>,
}

fn cases(data: &str, hex_fields: usize) -> Vec<Case> {
    data.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let f: Vec<&str> = l.split('|').collect();
            assert_eq!(f.len(), 3 + hex_fields, "malformed vector line: {}", &l[..l.len().min(60)]);
            Case {
                tc: f[0].to_string(),
                expect: f[1] == "P",
                fields: f[3..].iter().map(|h| hex::decode(h).expect("vector hex")).collect(),
            }
        })
        .collect()
}

/// The node's verdict on a v8 second leg, through the one chokepoint.
fn node_leg(pk: &[u8], msg: &[u8], sig: &[u8]) -> bool {
    verify_second_leg(V8, Some(ALG_SLH_DSA_SHA2_192F), msg, sig, pk).expect("v8 routes to FIPS 205")
}

/// RustCrypto's verdict, empty context (the v8 leg's interface). A key or a
/// signature it cannot even parse is a rejection.
fn rc_leg(pk: &[u8], msg: &[u8], sig: &[u8]) -> bool {
    match (VerifyingKey::<Sha2_192f>::try_from(pk), Signature::<Sha2_192f>::try_from(sig)) {
        (Ok(vk), Ok(s)) => vk.verify(msg, &s).is_ok(),
        _ => false,
    }
}

/// A check both implementations must refuse: what it is, then the key, the
/// message and the signature.
type Refused<'a> = (&'a str, &'a [u8], &'a [u8], &'a [u8]);

fn rc_sign(sk: &[u8], msg: &[u8]) -> Vec<u8> {
    SigningKey::<Sha2_192f>::try_from(sk).expect("RustCrypto parses the secret key").sign(msg).to_vec()
}

/// A key pair from fixed seeds, generated by both implementations, which must
/// produce the same secret key (and so the same public key, which it carries).
fn key_pair(i: usize) -> (Vec<u8>, Vec<u8>) {
    let seed: Vec<u8> = (0..SLH_DSA_SHA2_192F.seed_bytes()).map(|j| (i * 131 + j * 7 + 3) as u8).collect();
    let ours = SlhDsaKeyPair::from_seed(SLH_DSA_SHA2_192F, &seed).expect("keygen from seed");
    let n = seed.len() / 3;
    let theirs = SigningKey::<Sha2_192f>::slh_keygen_internal(&seed[..n], &seed[n..2 * n], &seed[2 * n..]);
    assert_eq!(theirs.to_vec(), ours.secret_key(), "key #{i}: the two keygens differ on the same seeds");
    (ours.secret_key().to_vec(), ours.public_key().to_vec())
}

#[test]
fn nist_vectors_get_the_same_verdict_from_both_implementations() {
    let v8 = cases(V8_LEG, 4);
    assert_eq!(v8.len(), 2, "v8-leg vector file truncated");
    let mut signed = 0;
    for c in &v8 {
        let (sk, pk, msg, sig) = (&c.fields[0], &c.fields[1], &c.fields[2], &c.fields[3]);
        assert!(c.expect, "tc{}: the v8-leg file holds valid signatures only", c.tc);
        assert!(node_leg(pk, msg, sig), "tc{}: the node rejects a NIST v8-leg signature", c.tc);
        assert!(rc_leg(pk, msg, sig), "tc{}: RustCrypto rejects a NIST v8-leg signature", c.tc);
        if !sk.is_empty() {
            assert!(rc_sign(sk, msg) == *sig, "tc{}: RustCrypto deterministic signing differs from NIST", c.tc);
            signed += 1;
        }
    }
    assert_eq!(signed, 1, "the deterministic signing case did not run");

    let external = cases(EXTERNAL, 4);
    assert_eq!(external.len(), 3, "external sigVer vector file truncated");
    for c in &external {
        let (ctx, pk, msg, sig) = (&c.fields[0], &c.fields[1], &c.fields[2], &c.fields[3]);
        let with_ctx = match (VerifyingKey::<Sha2_192f>::try_from(pk.as_slice()), Signature::<Sha2_192f>::try_from(sig.as_slice())) {
            (Ok(vk), Ok(s)) => vk.try_verify_with_context(msg, ctx, &s).is_ok(),
            _ => false,
        };
        assert_eq!(with_ctx, c.expect, "tc{}: RustCrypto disagrees with NIST", c.tc);
        // The v8 leg binds the empty context, so both must refuse a signature
        // made under any other context and accept one made under the empty one.
        assert_eq!(node_leg(pk, msg, sig), c.expect && ctx.is_empty(), "tc{}: node empty-context verdict", c.tc);
        assert_eq!(rc_leg(pk, msg, sig), node_leg(pk, msg, sig), "tc{}: empty-context verdicts differ", c.tc);
    }

    let internal = cases(INTERNAL, 3);
    assert_eq!(internal.len(), 4, "internal sigVer vector file truncated");
    for c in &internal {
        let (pk, msg, sig) = (&c.fields[0], &c.fields[1], &c.fields[2]);
        let theirs = match (VerifyingKey::<Sha2_192f>::try_from(pk.as_slice()), Signature::<Sha2_192f>::try_from(sig.as_slice())) {
            (Ok(vk), Ok(s)) => vk.slh_verify_internal(msg, &s).is_ok(),
            _ => false,
        };
        assert_eq!(theirs, c.expect, "tc{}: RustCrypto disagrees with NIST (internal)", c.tc);
        assert_eq!(slh_dsa::verify_internal(pk, sig, msg, SLH_DSA_SHA2_192F), c.expect, "tc{}: node library disagrees with NIST (internal)", c.tc);
    }
}

#[test]
fn fresh_keys_sign_and_verify_across_both_implementations() {
    let keys: Vec<_> = (0..6).map(key_pair).collect();
    for (i, (sk, pk)) in keys.iter().enumerate() {
        let len = [0usize, 1, 32, 3309, 4096, 100_000][i % 6] + i;
        let msg: Vec<u8> = (0..len).map(|j| (j * 13 + i) as u8).collect();

        let ours = slh_dsa::sign(sk, &msg, SLH_DSA_SHA2_192F);
        let theirs = rc_sign(sk, &msg);
        assert!(ours == theirs, "key #{i}, {len}-byte message: deterministic signatures differ");
        assert!(rc_leg(pk, &msg, &ours), "key #{i}: RustCrypto rejects the node's signature");
        assert!(node_leg(pk, &msg, &theirs), "key #{i}: the node rejects RustCrypto's signature");

        let mut changed = msg.clone();
        changed.push(0x55);
        let mut flipped = ours.clone();
        flipped[ours.len() / 2] ^= 0x01;
        let (_, other_pk) = &keys[(i + 1) % keys.len()];
        let refused: [Refused<'_>; 4] = [
            ("a changed message", pk, &changed, &ours),
            ("a flipped signature bit", pk, &msg, &flipped),
            ("another key", other_pk, &msg, &ours),
            ("a truncated signature", pk, &msg, &ours[..ours.len() - 1]),
        ];
        for (what, k, m, s) in refused {
            assert!(!node_leg(k, m, s), "key #{i}: the node accepts {what}");
            assert!(!rc_leg(k, m, s), "key #{i}: RustCrypto accepts {what}");
        }
    }
}

/// A whole v8 Profile A record whose second leg RustCrypto signed: it survives
/// the wire, the node accepts the leg over the record's own preimage, and the
/// leg equals the one the node would have signed.
#[test]
fn a_v8_record_leg_signed_by_rustcrypto_verifies_on_the_node() {
    let (slh_sk, slh_pk) = key_pair(99);
    let kp = DilithiumKeyPair::generate(dilithium::params::DilithiumMode::Dilithium3).expect("ML-DSA keygen");
    let mut rec = ValidationRecord::create(b"differential", kp.public_key().to_vec(), vec![], Classification::Public, None);
    rec.version = 8;
    rec.creator_sphincs_pk = Some(slh_pk.clone());
    rec.sphincs_algorithm = Some(ALG_SLH_DSA_SHA2_192F);
    let signable = rec.signable_bytes();
    rec.signature = Some(kp.sign(&signable, b"").expect("ML-DSA sign").as_bytes().to_vec());
    rec.sphincs_signature = Some(rc_sign(&slh_sk, &signable));

    let dec = ValidationRecord::from_bytes(&rec.to_bytes()).expect("v8 Profile A decodes");
    let signable = dec.signable_bytes();
    let leg = dec.sphincs_signature.clone().expect("second leg survives the wire");
    assert_eq!(dec.check_second_leg(&signable).expect("v8 leg routes"), Some(true), "the node rejects a RustCrypto-signed v8 leg");
    assert!(rc_leg(&slh_pk, &signable, &leg), "RustCrypto rejects its own leg after the wire");
    assert!(leg == slh_dsa::sign(&slh_sk, &signable, SLH_DSA_SHA2_192F), "the node would have signed another leg");

    // The leg is bound to this preimage: over a changed record, both refuse it.
    let mut other = dec.clone();
    other.content_hash[0] ^= 0x01;
    let other_signable = other.signable_bytes();
    assert_ne!(other_signable, signable);
    assert_eq!(other.check_second_leg(&other_signable).expect("v8 leg routes"), Some(false), "the node accepts the leg over another record");
    assert!(!rc_leg(&slh_pk, &other_signable, &leg), "RustCrypto accepts the leg over another record");
}
